#!/bin/bash
IP=`ifconfig -a | grep "inet" | grep -v 127.0.0.1 | grep -v "inet6" | awk '{print $2}'`
HOST_IP=10.0.10.114
HOST_PORT=9888
sed -i "s/{SERVER_IP_ADDR}/$IP/g" /etc/apache2/sites-available/poolserver.conf
sed -i "s/{SERVER_PORT}/${HOST_PORT}/g" /etc/apache2/sites-available/poolserver.conf
echo @@@@@ /etc/apache2/sites-available/poolserver.conf
grep Virtual /etc/apache2/sites-available/poolserver.conf
grep ServerName /etc/apache2/sites-available/poolserver.conf
sed -i "s/Listen 80/Listen ${HOST_PORT}/g" /etc/apache2/ports.conf
echo ===== /etc/apache2/ports.conf
grep Listen /etc/apache2/ports.conf

cat << EOC >>  .config/pnslocal.py
# auto-generated by entrypoint.sh to override above. DO not edit
pnsconfig['node'] = {'username': 'foo', 'password': 'bar', 
                     'host': '${HOST_IP}', 'port': ${HOST_PORT}}"
EOC
# >>  .config/pnslocal.py

tail -4 .config/pnslocal.py

