#!/bin/bash
# ./test n will test the nth subpackage.
# ./test will do all

OPT="--debug -v -r P "
OPT="-r P "
cd "$( dirname "${BASH_SOURCE[0]}" )"
n=$#
f=${1:-0}
if [ "$n" -eq "0" -o "$f" -eq "1" ]; then
    shift
    pytest $OPT $* tests/test_dataset.py;
fi
if [ $n -eq 0 -o $f -eq 2 ]; then
    shift
    pytest  $OPT $* tests/test_pal.py;
fi

if [ $n -eq 0 -o $f -eq 3 ]; then
    shift
    pytest  $OPT -k 'not server and not vpp' $* tests/test_pns.py;
fi

if [ $n -ne 0 -a $f -eq 4 ]; then
    shift
    pytest  $OPT -k 'server' $* tests/test_pns.py;
fi


